### ISSUE TITLE
Create-UML-scheme-for-all-entities

### ISSUE THREAD

**Issue by MichelRogov** [MichelRogov/Accounting#1]
We need relations and fields of all entities in our project
Use draw.io in order to create uml scheme for project
A.C.
Entities:
User
Group
Lessons/Timing
UserWebRequest (create)
Timing/Lesson - WebRequest
Teacher (Admin)
TeacherWebRequest
UserLessonsWebResponse

**Comment by LeSitar** [comment]
https://drive.google.com/file/d/1z-yyRrkSp10ErYhDwLtTjCJaheEYY_kD/view?usp=sharing
это ссылка, по которой можно смотреть схему проекта и оставлять свои комментарии
