### ISSUE TITLE
Fix SSL connection error in console

### ISSUE THREAD

**Issue by MichelRogov** [MichelRogov/Accounting#22]
When server is starting following appears in console:
`Wed Jun 05 20:08:22 IDT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
`
this needs to be fixed on app properties level.

**Comment by Koblov** [comment]
I did everything yesterday. Everything is working.
spring.datasource.url=jdbc:mysql://localhost:3306/accounting?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
 My Intellij is in conflict with Git. I fight for now

**Comment by Koblov** [comment]
https://github.com/MichelRogov/Accounting/tree/I-13

**Comment by Koblov** [comment]
https://github.com/MichelRogov/Accounting/tree/I-13 <https://github.com/MichelRogov/Accounting/tree/I-13>

Mit freundlichen Grüßen/ С Уважением
Viacheslav Koblov

**Comment by Koblov** [comment]
https://github.com/MichelRogov/Accounting/compare/I-22?expand=1

**Comment by SabadoshViktor** [comment]
https://github.com/MichelRogov/Accounting/pull/43

ср, 5 черв. 2019 о 19:11 MichelRogov <notifications@github.com> пише:
